epochs: 50
batch_size: 100
save_path: tmp/images
save_freq: 10

trainer:
  optimizer: adam
  lr: 0.001
  betas: [0.9, 0.999]
  weight_decay: 1.0e-6
  momentum: 0.9

  lr_scheduler: None

defense:
  method: None

mode: nearest
loss_fn: ce
momentum: 1.0
epsilon: 30
max_epsilon: 80
intervals: 80
num_steps: 20
kernel_size: 5
target_id: 0
shadow_id: 1 #for the attack
source_list: '2_4_6'
auxiliary_list: '1_3_5'
s_model_num: 1
a_model_num: 1
prob: 1.0
thres: 0.01  #if negative the auxiliary model will be the target model itself  
scale: 0.1
num_sample: 100
shadow_sample: 1000
num_classes: 10

multishot: True
thres_list: [0.001,0.0001,0.00001,0.000001]
# thres_list: [0.000001]
attack_method: GA_TDMI_fgsm

attack:
  getModelAcy: true
  attack: none
  save_tag: undefended
  fpr_threshold: 0.1

label_only: #settings for previous label-only attacks
  train_shadow: false #for transfer attack
  save_result: true
  generate_data: true #save metrics for different attacks
  attack: all
  blackadvattack: HopSkipJump
  aug_attack_type: r # d or r: please check the original paper https://arxiv.org/pdf/2007.14321.pdf
  aug_augment_kwarg: 9

