epochs: 50
batch_size: 50
save_path: tmp/images
save_freq: 10


mode: nearest
loss_fn: ce
momentum: 1.0
epsilon: 30
max_epsilon: 30
intervals: 20
num_steps: 20
kernel_size: 5
target_id: 0
shadow_id: 0 #for the attack
source_list: '1_3_5'
auxiliary_list: '2_4_6'
s_model_num: 1
a_model_num: 3
prob: 1.0
thres: 0.01  #if negative the auxiliary model will be the target model itself  
scale: 0.1
num_sample: 100
shadow_sample: 100
num_classes: 10

multishot: True
thres_list: [1.1,1.0,0.97,0.95,0.93,0.9,0.7,0.5,0.1,0.01,0.001,0.0001]

attack_method: GA_I_fgsm

attack:
  getModelAcy: true
  attack: none
  save_tag: undefended
  fpr_threshold: 0.1

label_only: #settings for previous label-only attacks
  train_shadow: False #for transfer attack
  save_result: True
  generate_data: True #save metrics for different attacks
  attack: all
  blackadvattack: all # for attack 2
  aug_attack_type: r # d or r: please check the original paper https://arxiv.org/pdf/2007.14321.pdf
  aug_augment_kwarg: 9